/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSplatRouteImport } from './routes/r/$'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ApiRuntimeDotjsRouteImport } from './routes/api/runtime[.]js'
import { Route as ApiRenderRouteImport } from './routes/api/render'
import { Route as ApiPreviewIndexRouteImport } from './routes/api/preview/index'
import { Route as ApiPreviewSplatRouteImport } from './routes/api/preview/$'
import { Route as ApiPreviewCompSplatRouteImport } from './routes/api/preview/comp/$'

const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSplatRoute = RSplatRouteImport.update({
  id: '/r/$',
  path: '/r/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeDotjsRoute = ApiRuntimeDotjsRouteImport.update({
  id: '/api/runtime.js',
  path: '/api/runtime.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderRoute = ApiRenderRouteImport.update({
  id: '/api/render',
  path: '/api/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewIndexRoute = ApiPreviewIndexRouteImport.update({
  id: '/api/preview/',
  path: '/api/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewSplatRoute = ApiPreviewSplatRouteImport.update({
  id: '/api/preview/$',
  path: '/api/preview/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewCompSplatRoute = ApiPreviewCompSplatRouteImport.update({
  id: '/api/preview/comp/$',
  path: '/api/preview/comp/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/api/render': typeof ApiRenderRoute
  '/api/runtime.js': typeof ApiRuntimeDotjsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/r/$': typeof RSplatRoute
  '/api/preview/$': typeof ApiPreviewSplatRoute
  '/api/preview/': typeof ApiPreviewIndexRoute
  '/api/preview/comp/$': typeof ApiPreviewCompSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/api/render': typeof ApiRenderRoute
  '/api/runtime.js': typeof ApiRuntimeDotjsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/r/$': typeof RSplatRoute
  '/api/preview/$': typeof ApiPreviewSplatRoute
  '/api/preview': typeof ApiPreviewIndexRoute
  '/api/preview/comp/$': typeof ApiPreviewCompSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/api/render': typeof ApiRenderRoute
  '/api/runtime.js': typeof ApiRuntimeDotjsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/r/$': typeof RSplatRoute
  '/api/preview/$': typeof ApiPreviewSplatRoute
  '/api/preview/': typeof ApiPreviewIndexRoute
  '/api/preview/comp/$': typeof ApiPreviewCompSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/api/render'
    | '/api/runtime.js'
    | '/demo/tanstack-query'
    | '/r/$'
    | '/api/preview/$'
    | '/api/preview/'
    | '/api/preview/comp/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/api/render'
    | '/api/runtime.js'
    | '/demo/tanstack-query'
    | '/r/$'
    | '/api/preview/$'
    | '/api/preview'
    | '/api/preview/comp/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai'
    | '/api/render'
    | '/api/runtime.js'
    | '/demo/tanstack-query'
    | '/r/$'
    | '/api/preview/$'
    | '/api/preview/'
    | '/api/preview/comp/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  ApiRenderRoute: typeof ApiRenderRoute
  ApiRuntimeDotjsRoute: typeof ApiRuntimeDotjsRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  RSplatRoute: typeof RSplatRoute
  ApiPreviewSplatRoute: typeof ApiPreviewSplatRoute
  ApiPreviewIndexRoute: typeof ApiPreviewIndexRoute
  ApiPreviewCompSplatRoute: typeof ApiPreviewCompSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$': {
      id: '/r/$'
      path: '/r/$'
      fullPath: '/r/$'
      preLoaderRoute: typeof RSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime.js': {
      id: '/api/runtime.js'
      path: '/api/runtime.js'
      fullPath: '/api/runtime.js'
      preLoaderRoute: typeof ApiRuntimeDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render': {
      id: '/api/render'
      path: '/api/render'
      fullPath: '/api/render'
      preLoaderRoute: typeof ApiRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview/': {
      id: '/api/preview/'
      path: '/api/preview'
      fullPath: '/api/preview/'
      preLoaderRoute: typeof ApiPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview/$': {
      id: '/api/preview/$'
      path: '/api/preview/$'
      fullPath: '/api/preview/$'
      preLoaderRoute: typeof ApiPreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview/comp/$': {
      id: '/api/preview/comp/$'
      path: '/api/preview/comp/$'
      fullPath: '/api/preview/comp/$'
      preLoaderRoute: typeof ApiPreviewCompSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  ApiRenderRoute: ApiRenderRoute,
  ApiRuntimeDotjsRoute: ApiRuntimeDotjsRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  RSplatRoute: RSplatRoute,
  ApiPreviewSplatRoute: ApiPreviewSplatRoute,
  ApiPreviewIndexRoute: ApiPreviewIndexRoute,
  ApiPreviewCompSplatRoute: ApiPreviewCompSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
